### PR TITLE
Ensure logger is provided

### PR DESCRIPTION
**Pull request by kgeckhart**
I started by fixing an issue where the logger wasn't being passed to the two AWS "interface" structs. I created some factory functions to use which should hopefully be more helpful vs the nil pointer crashes I got in dev. 

I also did some renames for clarity on the AWS adapters and took a pass for structured logging so logs should have the same properties now.

### CODE REVIEW

**Review by matthewnolf — APPROVED** [review]
LGTM. This does mean we're drifting more from upstream repo. Do we have thoughts on what the longer term plan is for managing that?

**Review by ferruvich — APPROVED** [review]
LGTM 👍 
Just wondering how many differences we're having from the forked repo, and the difficulty to eventually pull something useful from them.

**Comment by kgeckhart** [comment]
I'm still planning to submit PR's for all of this upstream after I get things tested.

**Comment by kgeckhart** [comment]
Thinking about it a bit more, I'm going to remove the renames from this PR since they are unrelated and are likely to cause more conflicts upstream.

**Pull request merged**
